apiVersion: v1
kind: Config
clusters:
- name: "rke2-1-jsccloud"
  cluster:
    server: "https://rancher.tc.humanbrainproject.eu/k8s/clusters/c-m-jcx2qhqn"

users:
- name: "rke2-1-jsccloud"
  user:
    token: "kubeconfig-u-4wxrsznsf9:6s2ctz66nwhq5ltlwmvc47rcw94852gkjzb685vpdg4jnmc2zk7lsz"


contexts:
- name: "rke2-1-jsccloud"
  context:
    user: "rke2-1-jsccloud"
    cluster: "rke2-1-jsccloud"
    namespace: metadata-wizard-dev

current-context: "rke2-1-jsccloud"
